replicaCount: 3

image:
  weather:
    repository: yarinch/weather
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
    

service:
  weather:
    name: my-weather-myweather-chart-weather
    type: NodePort
    port: 5000
    targetPort: 5000
    nodePort: 32000
 



